### PR TITLE
Fix data in delete events

### PR DESCRIPTION
**Pull request by racerpeter**

### CODE REVIEW

**Comment by racerpeter** [comment]
@mavenky @ahuth I just remembered why I didn't implement deletes this way (using old_row_data)-- it adds a ton of complexity to the changestream code if you can't assume that `rows` will always be there.

My recommendation is that we leave the functionality as-is.

**Comment by mavenky** [comment]
Why not have both `old_rows` and `rows`? I assume it will make it easier for any application consuming changestream to have both.

**Comment by racerpeter** [comment]
can you elaborate on what you mean by that oky?

**Comment by mavenky** [comment]
Meaning that for `create`, `update`, and `delete`, changestream outputs always have `old_rows` and `rows`. Right now, if you leave it as is, the consuming application will need to understand that `rows` for delete is what it was before since it will be deleted. It is intuitive for both `create`, and `updates`.

**Comment by racerpeter** [comment]
The way it currently works is that there is always a `rows` field in the JSON:

Create: `rows` is the new data (because there can only ever be new data)
Update: `rows` is the new values, `old_rows` is the previous values
Delete: `rows` is the rows that were deleted (because there is no old/new)

This is different than what I described initially (sorry, brain fart), and definitely worth documenting in this repo. I think you could make a good argument for both approaches (Delete has `old_rows` vs Delete has `rows`).

**Pull request closed without merging**
