### PR TITLE
Adds byte to the type of cases in the JsonFormatter

### PR DESCRIPTION
**Pull request by cpalafox**
Rapidash discovered an issue where TEXT and other blob columns where not being sent over to SQS, which makes a lot of the work that we are doing towards Subscribed Events kind of hard since a lot of our fields within our app are TEXT fields and tracking their changes seems relevant.

Through some digging, we figured out the problem is originated not in Changestream but within one of our dependencies, [mysql-binlog-connector](https://github.com/shyiko/mysql-binlog-connector-java/tree/dd710a5466381faa57442977b24fceff56a0820e), as it deserializes BLOB columns into byte arrays. 

The way the JsonFormatterActor checks for the type of the value, made it so that it didn't recognize the byte array and would just ignore that column as an unsupported value.

The changes done adds a case for byte arrays so that we can support it and forces it's casting into a string.

-------
### Notes

Personally, I have some worries regarding how this could impact our performance since now we would be doing ALL BLOBS, which could put us in a position where a huge BLOB gets transformed and sent as is.

The other concern is this case would capture all byte arrays, not necessarily sure how that could impact, or break, other BLOB fields

### CODE REVIEW

**Comment by diclophis** [comment]
This is an interesting problem case ...  what if we just synthesized a `*textfld*_dirty` field that was pre-computed before getting sent over SNS?

What sort of versioning support do we have on record-types that are audited?

If we allowed users to `revert-to-version: X` or `diff between version X Y`, we would only need the track who changed what field, and not necessarily what was changed in the given field value.

**Comment by jacksenechal** [comment]
Digging into the tests a bit on this I see there's a `blob_that_should_be_ignored` field on the fixtures table (`src/test/scala/changestream/helpers/Fixtures.scala`), implying that the omission was intentional. I do share your performance concerns @cpalafox. I also wonder if there's a size constraint on what we send to SQS, and what the implications would be of piping BLOBs through that.

At the moment we are only running changestream as a single process (well, two, but each for a distinct use case), and it has started to sweat a bit when we put it through really heavy loads, so I'd be wary of doing anything that slows it down. I think we need to put some work into this and see if we can get it into kubernetes and make it scale to multiple processes. My suspicion is that's doable, but I haven't seen the way clear through the woods completely. LMK if you guys would like to collab on that.

I was looking into getting it into kube last week, got a little stuck on some weirdness with duplicate actors being created, but once I figure that out I think it'll be GTG.

I also saw there's are some benchmark tests in the specs for changestream, so maybe adding one of those would be a way to quantify potential blob impact?

**Comment by cpalafox** [comment]
> This is an interesting problem case ... what if we just synthesized a `*textfld*_dirty` field that was pre-computed before getting sent over SNS?
> 
> What sort of versioning support do we have on record-types that are audited?
> 
> If we allowed users to `revert-to-version: X` or `diff between version X Y`, we would only need the track who changed what field, and not necessarily what was changed in the given field value.

We do not plan on allowing people to revert to a previous version, but the idea is that we can tell people what was the field before and after the change. And maybe there's exceptions to consider. Are `notes` for a `line_item` relevant if they changed? Maybe not?, but could a `Workspace.description` change be relevant for Audit Logs purposes? probably?

I don't know if just having a `field_dirty` would be useful in all scenarios?

**Comment by cpalafox** [comment]
> Digging into the tests a bit on this I see there's a `blob_that_should_be_ignored` field on the fixtures table (`src/test/scala/changestream/helpers/Fixtures.scala`), implying that the omission was intentional. I do share your performance concerns @cpalafox. I also wonder if there's a size constraint on what we send to SQS, and what the implications would be of piping BLOBs through that.
> 
> At the moment we are only running changestream as a single process (well, two, but each for a distinct use case), and it has started to sweat a bit when we put it through really heavy loads, so I'd be wary of doing anything that slows it down. I think we need to put some work into this and see if we can get it into kubernetes and make it scale to multiple processes. My suspicion is that's doable, but I haven't seen the way clear through the woods completely. LMK if you guys would like to collab on that.
> 
> I was looking into getting it into kube last week, got a little stuck on some weirdness with duplicate actors being created, but once I figure that out I think it'll be GTG.
> 
> I also saw there's are some benchmark tests in the specs for changestream, so maybe adding one of those would be a way to quantify potential blob impact?

@jacksenechal I'd be down to collab on getting it into kubes, as it would also allow us to run changestream on team sandboxes rather than depending on staging01 deploys. I don't know how much effort it'd take or how to do it, but definitely available to help out with the right guidance + pairing.

Good call on the benchmark test, this is definitely something we could do.

**Comment by jacksenechal** [comment]
@cpalafox this PR is ready to go for getting changestream onto team sandboxes. I've got it running now in the `master` sandbox, with the values specified in `charts/changestream/values-dev-example.yaml` there. I'm getting ready to roll the chart out to staging and prod.

Note that I haven't used the parent-child chart pattern with this one. It's just intended to be released manually via helm specifying the values file to use with `-f`. Feel free to make a copy of `values-dev-example.yaml` for your team and check that in if you want to keep it around.

**Comment by cpalafox** [comment]
@jacksenechal appreciate the update on this one, this will allow us to make some progress and do some debugging!

**Comment by diclophis** [comment]
We need to confirm what version of the AWS SDK we have linked in the build... It looks like before AWS SDK 1.12 SNS/SQS messages are limited in size to 256kb ... there is an additional set of libraries to add extended support for upto 2GB

https://docs.aws.amazon.com/sns/latest/dg/large-message-payloads.html
https://github.com/awslabs/amazon-sns-java-extended-client-lib/
https://github.com/dwhjames/aws-wrap/issues/58

Is it possible for the blobs in our database to be bigger than 256kb?

**Comment by cpalafox** [comment]
I think I could've explained better what's happening with the latest changes:

1. Take BLOB byte array, no matter how big it is
2. Compresses it using ZLib
3- Encodes it with Base64
4- Sends message with blob field as a string

So, for example:
**Scenario A: A very long text**

```
  blob = "VERY LONG" * 2000

---
string size: 18000
raw byte array size: 18000
compressed byte array size: 73
Encoded string size: 100
```

**Scenario B: Decently sized long text**

```
blob = "VERY LONG" * 100

----
string size: 900
raw byte array size: 900
compressed byte array size: 26
Encoded string size: 36
```

**Scenario C: A Short description**

```
blob = "dinner with client x, they accepted to renew our things. Good Soup"

-----
string size: 66
raw byte array size: 66
compressed byte array size: 70
Encoded string size: 96
```

**Scenario D: Emoji galore**

```
blob =  "🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄🙄" * 50

string size: 1100
raw byte array size: 2200
compressed byte array size: 28
Encoded string size: 40
```


Our current message size is about 2.5KB. With this compression + encoding, I'm not worried about performance impact or getting close to the 250KB limit

**Comment by cpalafox** [comment]
Dicussions and different efforts landed on going with truncation at the moment, those changes can be found on : https://github.com/mavenlink/changestream/pull/95

**Pull request closed without merging**
